workflows:
  flutter-workflow:
    name: Build Flutter app
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Run build
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
